- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.Brewfile: macos/Brewfile
- shell:
  - [defaults write com.apple.LaunchServices LSQuarantine -bool false, disable open app prompt]
- brewfile:
    file: macos/Brewfile
    stdout: true
    stderr: true
- shell:
  - [brew cleanup, Brew cleanup]
