- defaults:
    link:
      create: true
      relink: true
      force: true
    command:
      stdout: true
      stderr: true
- link:
    ~/.Brewfile: macos/Brewfile
- brewfile:
    file: macos/Brewfile
    stdout: true
    stderr: true
- shell:
  - [brew cleanup, Brew cleanup]
  - [pip3 install --user pynvim flake8, pip3 vim libraries]
  - [pip install --user pynvim flake8, pip vim libraries]
  - [sudo gem install neovim, Installing Ruby NeoVim Gem]
