- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.Brewfile_bash: macos/Brewfile_bash
- brewfile:
    file: macos/Brewfile_bash
    stdout: true
    stderr: true
- shell:
  - [scripts/osx_set_bash_default_shell.sh, Set brew bash to default shell]
