- defaults:
    link:
      create: true
      relink: true
      force: true
    command:
      stdout: true
      stderr: true
- link:
    ~/.Brewfile: macos/Brewfile
- brewfile:
    file: macos/Brewfile
    stdout: true
    stderr: true
- shell:
  - [brew cleanup, Brew cleanup]
