- defaults:
    link:
      create: true
      relink: true
      force: true
- shell:
  - [eval "$(fnm env --use-on-cd)" && fnm install --lts, Install and default latest lts node]
  - [eval "$(fnm env --use-on-cd)" && npm install --save-dev -g eslint && npm install -g npm@latest neovim yarn, Install npm eslint neovim yarn]
