- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdout: true
      stderr: true
- shell:
  - [pyenv install -s $(pyenv install -l | grep -v - | grep -v b | tail -1), Install latest stable python]
  # deal with pynvim bug
  - [pyenv install -s $(pyenv install -l | grep -v - | grep -v b | grep 3.7. | tail -1), Install latest stable python 3.7.x]
  - [pyenv global $(pyenv install -l | grep -v - | grep -v b | grep 3.7. | tail -1), Set global (default) python version]
  - [eval "$(pyenv init -)" && pip install --upgrade pip, pip upgrade]
  - [eval "$(pyenv init -)" && pip install --user pynvim flake8, pynvim flake8]
  - [pyenv rehash, Update shim executables]
