- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.bash_it:
      path: shells/bash/bash_it
    ~/.profile_shell:
      path: shells/bash/profile_bash
      if: >-
        [[ $(ps -p $$ | tail -1 | awk '{ print $4 }') =~ "bash" ]]
- shell:
  -
    command: bash -c "~/workspace/dotfiles/scripts/osx_set_bash_it_preferences.sh"
    description: Setting Bash-it defaults
    stdout: true
