- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.path: shells/path
    ~/.exports: shells/exports
    ~/.aliases: shells/aliases
    ~/.hushlogin: shells/hushlogin
    ~/.inputrc: shells/inputrc
    ~/.profile: shells/profile_common
    ~/.bashrc:
      path: shells/bash/bashrc
      if: >-
        [[ $(ps -p $$ | tail -1 | awk '{ print $4 }') =~ "bash" ]]
    ~/.zshrc:
      path: shells/zsh/zshrc
      if: >-
        [[ $(ps -p $$ | tail -1 | awk '{ print $4 }') =~ "zsh" ]]
