- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdout: true
      stderr: true
- link:
    ~/Library/Application Support/Spectacle/Shortcuts.json: apps/spectacle/spectacle.json
- shell:
  - [killall Spectacle, force Spectacle restart]
