- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true
- clean: [
    '~',
    '~/.config'
  ]
- shell:
  #- [git submodule update --init --recursive, Installing submodules]
  - [ echo "done" ]
