tap "homebrew/cask-drivers"
tap "universal-ctags/universal-ctags"
#tap "cantino/mcfly", "https://github.com/cantino/mcfly"

brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "wget"
brew "gnupg", link: true
brew "vim"
brew "neovim"

brew 'ag'
brew 'awscli'
brew 'confd'
brew 'direnv'
brew 'dive'
# https://github.com/kcrawford/dockutil/releases/
#brew 'dockutil'
brew 'duti'
brew 'fnm'
brew 'grep'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'libpq', link: true
brew "mcfly"
brew "md5sha1sum"
#brew 'nvm'
brew 'openssh'
brew 'packer'
brew 'pv'
brew 'pyenv'
brew 'python3'
brew 'rbenv'
brew 'rbenv-vars'
brew 'rclone'
brew 'rename'
brew 'ruby-build'
brew 'screen'
brew 'ssh-copy-id'
# sad. Download the pkgs manually: https://osxfuse.github.io/
#cask 'osxfuse'
#brew 'sshfs'
brew 'telnet'
brew 'tfenv'
brew 'universal-ctags', args: ["HEAD"]
brew 'vert'

cask 'android-file-transfer'
cask 'android-platform-tools'
cask 'android-sdk'
cask 'beardedspice'
cask 'caffeine'
#cask 'displaylink'
cask 'docker'
#cask 'dropbox'
cask 'flycut'
#cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'iterm2'
cask 'keybase'
cask 'licecap'
cask 'meetingbar'
cask 'ngrok'
cask 'rectangle'
cask 'sketch'
#cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'teamviewer'
cask 'vagrant'
cask 'vimr'
#cask 'virtualbox'
#cask 'virtualbox-extension-pack'
cask 'viscosity'
cask 'vlc'
