[ -n "$PS1" ] && source ~/.profile;

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /Users/yuhung-lin/workspace/maze/node_modules/tabtab/.completions/serverless.bash ] && . /Users/yuhung-lin/workspace/maze/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /Users/yuhung-lin/workspace/maze/node_modules/tabtab/.completions/sls.bash ] && . /Users/yuhung-lin/workspace/maze/node_modules/tabtab/.completions/sls.bash